#!/bin/bash

# Used by Binder, executed at the end to render jupyter notebook
# https://mybinder.readthedocs.io/en/latest/using/config_files.html#postbuild-run-code-after-installing-the-environment

# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy
# install the bokeh server extension so that
# bokeh launches at startup
mv bokehserverextension.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable bokeh extension
jupyter serverextension enable --sys-prefix bokehserverextension

# Install missing deps
pip install bokeh pandas
